/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.DefaultJasperReportsContext;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Asus
 */
public class DataTransaksiSewa extends javax.swing.JFrame {
Connection con;
  ResultSet rs;
  PreparedStatement pst;
    /**
     * Creates new form DataTransaksiSewa
     */
    public DataTransaksiSewa() {
        initComponents();
        setLocationRelativeTo(null);
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sewapc", "root", "");
        
        String sql = "SELECT * FROM tb_transaksisewa";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while (rs.next()){
         // menampilkan data transaksisewa ke table
         String IDSewa = String.valueOf(rs.getString("IDSewa"));
         String IDPembeli = String.valueOf(rs.getString("IDPembeli"));
         String NoPC = String.valueOf(rs.getString("NoPC"));
         String Harga = String.valueOf(rs.getString("Harga"));
         String HariSewa = String.valueOf(rs.getString("HariSewa"));
         String Biaya = String.valueOf(rs.getString("Biaya"));
         
         
         String tbDataTransaksiSewa[] = {IDSewa, IDPembeli, NoPC, Harga, HariSewa, Biaya, };
         DefaultTableModel tampilModel = (DefaultTableModel) tbltransaksisewa.getModel();

         tampilModel.addRow(tbDataTransaksiSewa);
         }
                
     } catch (ClassNotFoundException ex) {
            Logger.getLogger(DataPC.class.getName()).log(Level.SEVERE, "MySQL JDBC Driver not found", ex);
        } catch (SQLException ex) {
            Logger.getLogger(DataPC.class.getName()).log(Level.SEVERE, null, ex);
        }
        //select JenisKelamin
        try {
        String sql = "SELECT * FROM tb_transaksisewa";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            
        }
        } catch (Exception e){
    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfidsewa = new javax.swing.JTextField();
        tfidpembeli = new javax.swing.JTextField();
        tfharga = new javax.swing.JTextField();
        tfjumlahharisewa = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btcetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltransaksisewa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tfbiaya = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfnopc = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu Transaksi Sewa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Sewa");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID Pembeli");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("No PC");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Hari Sewa");

        bttambah.setText("TAMBAH");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        btubah.setText("UBAH");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btcetak.setText("CETAK");
        btcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcetakActionPerformed(evt);
            }
        });

        tbltransaksisewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDSewa", "IDPembeli", "NoPC", "Harga", "JumlahHariSewa", "Biaya"
            }
        ));
        tbltransaksisewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltransaksisewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltransaksisewa);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel8.setText("Biaya");

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(bttambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bthapus)
                        .addGap(29, 29, 29)
                        .addComponent(btcetak)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfidsewa)
                                    .addComponent(tfjumlahharisewa)
                                    .addComponent(tfharga)
                                    .addComponent(tfidpembeli)
                                    .addComponent(tfbiaya)
                                    .addComponent(tfnopc)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(37, 37, 37)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfidsewa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfidpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnopc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfjumlahharisewa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(tfbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcetak)
                    .addComponent(bthapus)
                    .addComponent(btubah)
                    .addComponent(bttambah)
                    .addComponent(jButton2))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
         //Mengecek pemilihan data
if (tfidsewa.getText().equals("") || tfidpembeli.getText().equals("") ||tfnopc.getText().equals("")  ||
    tfharga.getText().equals("") || tfjumlahharisewa.getText().equals("") ||  tfbiaya.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
            "Error", JOptionPane.WARNING_MESSAGE);
        }else{
    
        
        //Konfirmasi ubah data  
        int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin mengubah data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (ubah == JOptionPane.YES_OPTION) {
                    
        // Mengubah data dalam database

            try {
                    // Mengubah data dalam database
            pst = con.prepareStatement("UPDATE tb_transaksisewa SET IDSewa=?, IDPembeli=?, NoPC=?, Harga=?, HariSewa=?, Biaya=?  WHERE IDSewa=?");
            pst.setString(1, tfidsewa.getText());
            pst.setString(2, tfidpembeli.getText());
            pst.setString(3, tfnopc.getText());
            int Harga = Integer.parseInt(tfharga.getText());
            pst.setString(4, tfharga.getText());
            pst.setString(5, tfjumlahharisewa.getText());
            int Biaya = Integer.parseInt(tfbiaya.getText());
            pst.setString(6, tfbiaya.getText());
            pst.setString(7, tfidsewa.getText());
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                                         
            // Mengubah data dalam row di tabel
            int selectedRow = tbltransaksisewa.getSelectedRow();
            if (selectedRow >= 0) {
                DefaultTableModel model = (DefaultTableModel) tbltransaksisewa.getModel();
                model.setValueAt(tfidsewa.getText(), selectedRow, 0);
                model.setValueAt(tfidpembeli.getText(), selectedRow, 1);
                 model.setValueAt(tfnopc.getText(), selectedRow, 2);
                model.setValueAt(tfharga.getText(), selectedRow, 3);
                model.setValueAt(tfjumlahharisewa.getText(), selectedRow, 4);
                model.setValueAt(tfbiaya.getText(), selectedRow, 5);
               
                // Membersihkan input setelah berhasil mengubah data
            tfidsewa.setText("");
            tfidpembeli.setText("");
              tfnopc.setText("");
            tfharga.setText("");
            tfjumlahharisewa.setText("");
            tfbiaya.setText("");
            tfidsewa.requestFocus();

            }
                } catch (SQLException ex) {
                Logger.getLogger(DataTransaksiSewa.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
}
    }//GEN-LAST:event_btubahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
             //Mengecek pemilihan data
        if (tfidsewa.getText().equals("") || tfidpembeli.getText().equals("") || 
            tfnopc.getText().equals("") || tfharga.getText().equals("") || tfjumlahharisewa.getText().equals("") ||
             tfbiaya.getText().equals("")   ) {
            JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu..!",
            "Error", JOptionPane.WARNING_MESSAGE);
     }else{
    //Konfirmasi hapus data
    int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
           if (ubah == JOptionPane.YES_OPTION) {
               
    // Menghapus data dalam database
        try {
    pst = con.prepareStatement("DELETE FROM tb_transaksisewa WHERE IDSewa=?");
    pst.setString(1, tfidpembeli.getText());
    pst.executeUpdate();
    pst.close(); // Menutup PreparedStatement setelah digunakan
    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

    } catch (SQLException ex) {
        Logger.getLogger(DataPembeli.class.getName()).log(Level.SEVERE, null, ex);
    }
        //Menghapus data dalam row
    int getSelectedRowForDeletion = tbltransaksisewa.getSelectedRow();
    if (getSelectedRowForDeletion >= 0) {
        DefaultTableModel model = (DefaultTableModel) tbltransaksisewa.getModel();
        model.removeRow(getSelectedRowForDeletion);
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus"); 
         }
        
        //Membersihkan inputan
        tfidsewa.setText("");
        tfidpembeli.setText("");
         tfnopc.setText("");
        tfharga.setText(null);
        tfjumlahharisewa.setText("");
        tfbiaya.setText("");
        tfidsewa.requestFocus();
           }
        }
        
        
    }//GEN-LAST:event_bthapusActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
              //Mengecek nilai yang di input
if (tfidsewa.getText().equals("") || tfidpembeli.getText().equals("") || tfnopc.getText().equals("")  ||
    tfharga.getText().equals("") || tfjumlahharisewa.getText().equals("") || tfbiaya.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
            "Error", JOptionPane.WARNING_MESSAGE);
} else {
    // Pemeriksaan ID tidak boleh sama
    boolean IDSudahAda = false;
    DefaultTableModel model = (DefaultTableModel) tbltransaksisewa.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        if (tfidsewa.getText().equals(model.getValueAt(i, 0))) {
            IDSudahAda = true;
            break;
        }
    }

    if (IDSudahAda) {
        JOptionPane.showMessageDialog(null, "ID sudah terdaftar, masukkan ID yang berbeda",
                "Error", JOptionPane.WARNING_MESSAGE);
    tfidsewa.requestFocus();
    } else {
        
   //Membuat koneksi agar dapat menipulasi data TransaksiSewa pada Database    
try {
    pst = con.prepareStatement("INSERT into tb_transaksisewa(IDSewa,IDPembeli,NoPC,Harga,HariSewa,Biaya)values(?,?,?,?,?,?)");
    pst.setString(1, tfidsewa.getText());
    pst.setString(2, tfidpembeli.getText());
    pst.setString(3, tfnopc.getText());
    pst.setString(4, tfharga.getText());
    pst.setString(5, tfjumlahharisewa.getText());
    pst.setString(6, tfbiaya.getText());
    pst.executeUpdate();
    
} catch (SQLException ex) {
    Logger.getLogger(DataTransaksiSewa.class.getName()).log(Level.SEVERE, null, ex);
}
        
        // Menambahkan data ke dalam row
    int harga = Integer.parseInt(tfharga.getText());
    int biaya  = Integer.parseInt(tfbiaya.getText());
    model.addRow(new Object[]{tfidsewa.getText(), tfidpembeli.getText(),tfnopc.getText() ,tfharga.getText() ,
                              tfjumlahharisewa.getText(), harga, biaya});
    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
   //Membersihkan field setelah data berhasil terinput
        tfidsewa.setText("");
        tfidpembeli.setText("");
        tfnopc.setText(""); 
        tfharga.setText("");
        tfjumlahharisewa.setText("");
        tfbiaya.setText("");
      
        }     
}
    }//GEN-LAST:event_bttambahActionPerformed

    private void tbltransaksisewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltransaksisewaMouseClicked

       
    int selectedRow = tbltransaksisewa.getSelectedRow();

        // Menampilkan data dari baris yang dipilih di TextField
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tbltransaksisewa.getModel();
            tfidsewa.setText(model.getValueAt(selectedRow, 0).toString());
            tfidpembeli.setText(model.getValueAt(selectedRow, 1).toString());
            tfnopc.setText(model.getValueAt(selectedRow, 2).toString());
            tfharga.setText(model.getValueAt(selectedRow, 3).toString());
            tfjumlahharisewa.setText(model.getValueAt(selectedRow, 4).toString());
            tfbiaya.setText(model.getValueAt(selectedRow, 5).toString());
        }
        
            
    }//GEN-LAST:event_tbltransaksisewaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menuutama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tfidsewa.setText("");
        tfidpembeli.setText("");
        tfnopc.setText("");
        tfharga.setText("");
        tfjumlahharisewa.setText("");
        tfbiaya.setText("");
        tfidsewa.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetakActionPerformed
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sewapc", "root", "");

        HashMap<String, Object> parameters = new HashMap<>();
        String reportpath = "src/laporan/LaporanDataTransaksisewa.jrxml";
        JasperReport jr = JasperCompileManager.compileReport(reportpath);
        
        // Add the following line to resolve the namespace warning
        JasperReportsContext jasperReportsContext = DefaultJasperReportsContext.getInstance();
        jasperReportsContext.setProperty("net.sf.jasperreports.components.html.factory", "net.sf.jasperreports.components.html.HtmlComponentFactory");

        JasperPrint jp = JasperFillManager.fillReport(jr, parameters, conn);
        JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setVisible(true);
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_btcetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTransaksiSewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcetak;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tbltransaksisewa;
    private javax.swing.JTextField tfbiaya;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfidpembeli;
    private javax.swing.JTextField tfidsewa;
    private javax.swing.JTextField tfjumlahharisewa;
    private javax.swing.JTextField tfnopc;
    // End of variables declaration//GEN-END:variables
}
