/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.DefaultJasperReportsContext;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.view.JasperViewer;
/**l *
 * @author Asus
 */
public class DataPC extends javax.swing.JFrame {

 Connection con;
  ResultSet rs;
  PreparedStatement pst;
    /**
     * Creates new form DataPC
     */
    public DataPC() {
        initComponents();
        setLocationRelativeTo(null);
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sewapc", "root", "");
        
        String sql = "SELECT * FROM tb_datapc";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while (rs.next()){
         // menampilkan data pc ke table
         String NoPC = String.valueOf(rs.getString("NoPC"));
         String MerekPC = String.valueOf(rs.getString("MerekPC"));
         String JenisPC = String.valueOf(rs.getString("JenisPC"));
         String HargaSewa = String.valueOf(rs.getString("HargaSewa"));
         String Stok = String.valueOf(rs.getString("Stok"));
         
         
         String tbDataPC[] = {NoPC, MerekPC, JenisPC, HargaSewa, Stok, };
         DefaultTableModel tampilModel = (DefaultTableModel) tbldatapc.getModel();

         tampilModel.addRow(tbDataPC);
         }
                
     } catch (ClassNotFoundException ex) {
            Logger.getLogger(DataPC.class.getName()).log(Level.SEVERE, "MySQL JDBC Driver not found", ex);
        } catch (SQLException ex) {
            Logger.getLogger(DataPC.class.getName()).log(Level.SEVERE, null, ex);
        }
        //select JenisPC
        try {
        String sql = "SELECT * FROM tb_jenis";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            cmbjenispc.addItem(rs.getString("nama"));
        }
        } catch (Exception e){
    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatapc = new javax.swing.JTable();
        tfmerek = new javax.swing.JTextField();
        tfharga = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tfstok = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        cmbjenispc = new javax.swing.JComboBox<>();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Stok");

        tbldatapc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NoPC", "MerekPC", "JenisPC", "HargaSewa", "Stok"
            }
        ));
        tbldatapc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatapcMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldatapc);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        cmbjenispc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis--" }));

        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu Data PC");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("No PC");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Merek PC");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Jenis PC");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Harga Sewa");

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfno)
                            .addComponent(tfstok)
                            .addComponent(tfharga)
                            .addComponent(tfmerek)
                            .addComponent(cmbjenispc, 0, 173, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btntambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnubah)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus)
                        .addGap(18, 18, 18)
                        .addComponent(btncetak)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfmerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbjenispc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfstok, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnubah)
                    .addComponent(btnhapus)
                    .addComponent(btncetak)
                    .addComponent(btntambah)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
       //Mengecek nilai yang di input
if (tfno.getText().equals("") || tfmerek.getText().equals("") || cmbjenispc.getSelectedItem().equals("--Pilih Jenis--") ||
    tfharga.getText().equals("") || tfstok.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
            "Error", JOptionPane.WARNING_MESSAGE);
} else {
    // Pemeriksaan ID tidak boleh sama
    boolean noSudahAda = false;
    DefaultTableModel model = (DefaultTableModel) tbldatapc.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        if (tfno.getText().equals(model.getValueAt(i, 0))) {
            noSudahAda = true;
            break;
        }
    }

    if (noSudahAda) {
        JOptionPane.showMessageDialog(null, "No sudah terdaftar, masukkan No yang berbeda",
                "Error", JOptionPane.WARNING_MESSAGE);
    tfno.requestFocus();
    } else {
        
   //Membuat koneksi agar dapat menipulasi data PC pada Database    
try {
    pst = con.prepareStatement("INSERT into tb_datapc(NoPC,MerekPC,JenisPC,HargaSewa,Stok)values(?,?,?,?,?)");
    pst.setString(1, tfno.getText());
    pst.setString(2, tfmerek.getText());
    pst.setString(3, cmbjenispc.getSelectedItem().toString());
    pst.setString(4, tfharga.getText());
    pst.setString(5, tfstok.getText());
    pst.executeUpdate();
    
} catch (SQLException ex) {
    Logger.getLogger(DataPC.class.getName()).log(Level.SEVERE, null, ex);
}
        
        // Menambahkan data ke dalam row
    int hargasewa = Integer.parseInt(tfharga.getText());
    int stok   = Integer.parseInt(tfstok.getText());
    model.addRow(new Object[]{tfno.getText(), tfmerek.getText(), cmbjenispc.getSelectedItem().toString(),
                              tfharga.getText(), stok, hargasewa});
    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
   //Membersihkan field setelah data berhasil terinput
        tfno.setText("");
        tfmerek.setText("");
         cmbjenispc.setSelectedItem("--Pilih Pemasok--");
        tfharga.setText("");
        tfstok.setText("");
      
        }     
}
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        //Mengecek pemilihan data
if (tfno.getText().equals("") || tfmerek.getText().equals("") || cmbjenispc.getSelectedItem().equals("--Pilih Jenis--") ||
    tfharga.getText().equals("") || tfstok.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
            "Error", JOptionPane.WARNING_MESSAGE);
        }else{
    
        
        //Konfirmasi ubah data  
        int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin mengubah data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (ubah == JOptionPane.YES_OPTION) {
                    
        // Mengubah data dalam database

            try {
                    // Mengubah data dalam database
            pst = con.prepareStatement("UPDATE tb_datapc SET NoPC=?, MerekPC=?, JenisPC=?, HargaSewa=?, Stok=? WHERE NoPC=?");
            pst.setString(1, tfno.getText());
            pst.setString(2, tfmerek.getText());
            pst.setString(3, cmbjenispc.getSelectedItem().toString());
            int HargaSewa = Integer.parseInt(tfharga.getText());
            pst.setString(4, tfharga.getText());
            int Stok = Integer.parseInt(tfstok.getText());
            pst.setString(5, tfstok.getText());
            pst.setString(6, tfno.getText());
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                                         
            // Mengubah data dalam row di tabel
            int selectedRow = tbldatapc.getSelectedRow();
            if (selectedRow >= 0) {
                DefaultTableModel model = (DefaultTableModel) tbldatapc.getModel();
                model.setValueAt(tfno.getText(), selectedRow, 0);
                model.setValueAt(tfmerek.getText(), selectedRow, 1);
                model.setValueAt(cmbjenispc.getSelectedItem().toString(), selectedRow, 2);
                model.setValueAt(tfharga.getText(), selectedRow, 3);
                model.setValueAt(tfstok.getText(), selectedRow, 4);
               
                // Membersihkan input setelah berhasil mengubah data
            tfno.setText("");
            tfmerek.setText("");
            cmbjenispc.setSelectedItem("Komputer");
            tfharga.setText("");
            tfstok.setText("");
            tfno.requestFocus();

            }
                } catch (SQLException ex) {
                Logger.getLogger(DataPC.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
}
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
      
//Mengecek pemilihan data
        if (tfno.getText().equals("") || tfmerek.getText().equals("") || 
            cmbjenispc.getSelectedItem().equals("--Pilih Jenis--") || tfharga.getText().equals("") || tfstok.getText().equals("")   ) {
            JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu..!",
            "Error", JOptionPane.WARNING_MESSAGE);
     }else{
    //Konfirmasi hapus data
    int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
           if (ubah == JOptionPane.YES_OPTION) {
               
    // Menghapus data dalam database
        try {
    pst = con.prepareStatement("DELETE FROM tb_datapc WHERE NoPC=?");
    pst.setString(1, tfno.getText());
    pst.executeUpdate();
    pst.close(); // Menutup PreparedStatement setelah digunakan
    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

    } catch (SQLException ex) {
        Logger.getLogger(DataPC.class.getName()).log(Level.SEVERE, null, ex);
        
    }
        //Menghapus data dalam row
    int getSelectedRowForDeletion = tbldatapc.getSelectedRow();
    if (getSelectedRowForDeletion >= 0) {
        DefaultTableModel model = (DefaultTableModel) tbldatapc.getModel();
        model.removeRow(getSelectedRowForDeletion);
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus"); 
         }
        
        //Membersihkan inputan
        tfno.setText("");
        tfmerek.setText("");
        cmbjenispc.setSelectedItem("--Pilih Jenis--");
        tfharga.setText(null);
        tfstok.setText(null);
        tfno.requestFocus();
           }
        }
        
       
        
        
    
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbldatapcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatapcMouseClicked
        //TAMPIL        
        int selectedRow = tbldatapc.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) tbldatapc.getModel();
        tfno.setText(model.getValueAt(selectedRow, 0).toString());
        tfmerek.setText(model.getValueAt(selectedRow, 1).toString());
        String comboSub = model.getValueAt(selectedRow, 2).toString();
        for (int i = 0; i < cmbjenispc.getItemCount(); i++) {
            if (cmbjenispc.getItemAt(i).toString().equalsIgnoreCase(comboSub)) {
        cmbjenispc.setSelectedIndex(i);
        break;
         }
        tfharga.setText(model.getValueAt(selectedRow, 3).toString());
        tfstok.setText(model.getValueAt(selectedRow, 4).toString());
       
        

        
    }
    }//GEN-LAST:event_tbldatapcMouseClicked

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sewapc", "root", "");

        HashMap<String, Object> parameters = new HashMap<>();
        String reportpath = "src/laporan/LaporanDataPC.jrxml";
        JasperReport jr = JasperCompileManager.compileReport(reportpath);
        
        // Add the following line to resolve the namespace warning
        JasperReportsContext jasperReportsContext = DefaultJasperReportsContext.getInstance();
        jasperReportsContext.setProperty("net.sf.jasperreports.components.html.factory", "net.sf.jasperreports.components.html.HtmlComponentFactory");

        JasperPrint jp = JasperFillManager.fillReport(jr, parameters, conn);
        JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setVisible(true);
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_btncetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Menuutama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 tfno.setText("");
        tfmerek.setText("");
        cmbjenispc.setSelectedItem("--Pilih Jenis--");
        tfharga.setText("");
        tfstok.setText("");
        tfno.requestFocus();     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cmbjenispc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tbldatapc;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfmerek;
    private javax.swing.JTextField tfno;
    private javax.swing.JTextField tfstok;
    // End of variables declaration//GEN-END:variables
}
