/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class DataPembeli extends javax.swing.JFrame {
Connection con;
  ResultSet rs;
  PreparedStatement pst;
    /**
     * Creates new form DataPembeli
     */
    public DataPembeli() {
        initComponents();
        setLocationRelativeTo(null);
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sewapc", "root", "");
        
        String sql = "SELECT * FROM tb_pembeli";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while (rs.next()){
         // menampilkan data pc ke table
         String IDPembeli = String.valueOf(rs.getString("IDPembeli"));
         String NamaLengkap = String.valueOf(rs.getString("NamaLengkap"));
         String JenisKelamin = String.valueOf(rs.getString("JenisKelamin"));
         String Alamat = String.valueOf(rs.getString("Alamat"));
         String NoTelpon = String.valueOf(rs.getString("NoTelpon"));
         
         
         String tbDataPembeli[] = {IDPembeli, NamaLengkap, JenisKelamin, Alamat, NoTelpon, };
         DefaultTableModel tampilModel = (DefaultTableModel) tbldatapembeli.getModel();

         tampilModel.addRow(tbDataPembeli);
         }
                
     } catch (ClassNotFoundException ex) {
            Logger.getLogger(DataPembeli.class.getName()).log(Level.SEVERE, "MySQL JDBC Driver not found", ex);
        } catch (SQLException ex) {
            Logger.getLogger(DataPembeli.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        ButtonGroup buttonGroup = new ButtonGroup();
    buttonGroup.add(rbLaki);
    buttonGroup.add(rbPerempuan);
    rbLaki.setSelected(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfidpembeli = new javax.swing.JTextField();
        tfnamalengkap = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        tfnotelepon = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btcetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatapembeli = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        btCLEAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu Pembeli");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Pembeli");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("No Telepon");

        bttambah.setText("TAMBAH");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        btubah.setText("UBAH");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btcetak.setText("CETAK");
        btcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcetakActionPerformed(evt);
            }
        });

        tbldatapembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPembeli", "NamaLengkap", "JenisKelamin", "Alamat", "NoTelepon"
            }
        ));
        tbldatapembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatapembeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldatapembeli);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        rbLaki.setText("LAKI LAKI");

        rbPerempuan.setText("PEREMPUAN");

        btCLEAR.setText("CLEAR");
        btCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCLEARActionPerformed(evt);
            }
        });

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfidpembeli)
                                    .addComponent(tfnotelepon)
                                    .addComponent(tfalamat)
                                    .addComponent(tfnamalengkap)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bttambah)
                        .addGap(18, 18, 18)
                        .addComponent(btubah)
                        .addGap(18, 18, 18)
                        .addComponent(bthapus)
                        .addGap(26, 26, 26)
                        .addComponent(btcetak)
                        .addGap(18, 18, 18)
                        .addComponent(btCLEAR)
                        .addGap(0, 375, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfidpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbPerempuan)
                                .addComponent(rbLaki)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnotelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(51, 51, 51)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btubah)
                    .addComponent(bthapus)
                    .addComponent(btcetak)
                    .addComponent(bttambah)
                    .addComponent(btCLEAR))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        //Mengecek pemilihan data
        if (tfidpembeli.getText().equals("") || tfnamalengkap.getText().equals("") || 
             tfalamat.getText().equals("") || tfnotelepon.getText().equals("")   ) {
            JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu..!",
            "Error", JOptionPane.WARNING_MESSAGE);
     }else{
    //Konfirmasi hapus data
    int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
           if (ubah == JOptionPane.YES_OPTION) {
               
    // Menghapus data dalam database
        try {
    pst = con.prepareStatement("DELETE FROM tb_pembeli WHERE IDPembeli=?");
    pst.setString(1, tfidpembeli.getText());
    pst.executeUpdate();
    pst.close(); // Menutup PreparedStatement setelah digunakan
    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

    } catch (SQLException ex) {
        Logger.getLogger(DataPembeli.class.getName()).log(Level.SEVERE, null, ex);
    }
         //Menghapus data dalam row
    int getSelectedRowForDeletion = tbldatapembeli.getSelectedRow();
    if (getSelectedRowForDeletion >= 0) {
        DefaultTableModel model = (DefaultTableModel) tbldatapembeli.getModel();
        model.removeRow(getSelectedRowForDeletion);
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus"); 
         }
        
        //Membersihkan inputan
        tfidpembeli.setText("");
        tfnamalengkap.setText("");
        rbLaki.setSelected(false);
        rbPerempuan.setSelected(false);
        tfalamat.setText("");
        tfnotelepon.setText("");
        tfidpembeli.requestFocus();
           }
        }
        
       
        
    }//GEN-LAST:event_bthapusActionPerformed

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
          //Mengecek pemilihan data
if (tfidpembeli.getText().equals("") || tfnamalengkap.getText().equals("") || 
    tfalamat.getText().equals("") || tfnotelepon.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
            "Error", JOptionPane.WARNING_MESSAGE);
        }else{
    
        
        //Konfirmasi ubah data  
        int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin mengubah data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (ubah == JOptionPane.YES_OPTION) {
                    
        // Mengubah data dalam database

            try {
                    // Mengubah data dalam database
            pst = con.prepareStatement("UPDATE tb_pembeli SET IDPembeli=?, NamaLengkap=?, JenisKelamin=?, Alamat=?, NoTelpon=? WHERE IDPembeli=?");
            pst.setString(1, tfidpembeli.getText());
            pst.setString(2, tfnamalengkap.getText());
            if (rbLaki.isSelected()) {
            pst.setString(3, "Laki-Laki");
            } else if (rbPerempuan.isSelected()) {
             pst.setString(3, "Perempuan");
             }
            pst.setString(4, tfalamat.getText());
            pst.setString(5, tfnotelepon.getText());
            pst.setString(6, tfidpembeli.getText());
       
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                                         
            // Mengubah data dalam row di tabel
            int selectedRow = tbldatapembeli.getSelectedRow();
            if (selectedRow >= 0) {
                DefaultTableModel model = (DefaultTableModel) tbldatapembeli.getModel();
                model.setValueAt(tfidpembeli.getText(), selectedRow, 0);
                model.setValueAt(tfnamalengkap.getText(), selectedRow, 1);
                String jenisKelamin = model.getValueAt(selectedRow, 2).toString();
             if ("Laki-Laki".equals(jenisKelamin)) {
            rbLaki.setSelected(true);
            rbPerempuan.setSelected(false);
               } else if ("Perempuan".equals(jenisKelamin)) {
            rbLaki.setSelected(false);
            rbPerempuan.setSelected(true);
        }
                model.setValueAt(tfalamat.getText(), selectedRow, 3);
                model.setValueAt(tfnotelepon.getText(), selectedRow, 4);
               
                // Membersihkan input setelah berhasil mengubah data
            tfidpembeli.setText("");
            tfnamalengkap.setText("");
            tfalamat.setText("");
            tfnotelepon.setText("");
            tfidpembeli.requestFocus();

            }
                } catch (SQLException ex) {
                Logger.getLogger(DataPembeli.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
}
    }//GEN-LAST:event_btubahActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
             //Mengecek nilai yang di input
if (tfidpembeli.getText().equals("") || tfnamalengkap.getText().equals("") || 
    tfalamat.getText().equals("") || tfnotelepon.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
            "Error", JOptionPane.WARNING_MESSAGE);
} else {
    // Pemeriksaan ID tidak boleh sama
    boolean IDSudahAda = false;
    DefaultTableModel model = (DefaultTableModel) tbldatapembeli.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        if (tfidpembeli.getText().equals(model.getValueAt(i, 0))) {
            IDSudahAda = true;
            break;
        }
    }

    if (IDSudahAda) {
        JOptionPane.showMessageDialog(null, "ID sudah terdaftar, masukkan ID yang berbeda",
                "Error", JOptionPane.WARNING_MESSAGE);
    tfidpembeli.requestFocus();
    } else {
        
   //Membuat koneksi agar dapat menipulasi data Pembeli pada Database    
try {
    pst = con.prepareStatement("INSERT INTO tb_pembeli(IDPembeli, NamaLengkap, JenisKelamin, Alamat, NoTelpon) VALUES (?, ?, ?, ?, ?)");
    int id = Integer.parseInt(tfidpembeli.getText());
    pst.setString(1, tfidpembeli.getText());
    pst.setString(2, tfnamalengkap.getText());
    if (rbLaki.isSelected()) {
        pst.setString(3, "Laki-Laki");
        } else if (rbPerempuan.isSelected()) {
        pst.setString(3, "Perempuan");
        }
    pst.setString(4, tfalamat.getText());
    pst.setString(5, tfnotelepon.getText());
    pst.executeUpdate();
    
} catch (SQLException ex) {
    Logger.getLogger(DataPembeli.class.getName()).log(Level.SEVERE, null, ex);
}
        
        // Menambahkan data ke dalam row
  int id = Integer.parseInt(tfidpembeli.getText());
    String jenisKelamin = null;
    if (rbLaki.isSelected()) {
        jenisKelamin = "Laki-Laki";
    } else if (rbPerempuan.isSelected()) {
        jenisKelamin = "Perempuan";
    } 
    model.addRow(new Object[]{tfidpembeli.getText(), tfnamalengkap.getText(), jenisKelamin,
                              tfalamat.getText(), tfnotelepon.getText()});
    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
   //Membersihkan field setelah data berhasil terinput
        tfidpembeli.setText("");
        tfnamalengkap.setText("");
        tfalamat.setText("");
        tfnotelepon.setText("");
      
        }     
}
    
    }//GEN-LAST:event_bttambahActionPerformed

    private void tbldatapembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatapembeliMouseClicked
        //TAMPIL        
        int selectedRow = tbldatapembeli.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) tbldatapembeli.getModel();
        tfidpembeli.setText(model.getValueAt(selectedRow, 0).toString());
        tfnamalengkap.setText(model.getValueAt(selectedRow, 1).toString());
        String jenisKelamin = model.getValueAt(selectedRow, 2).toString();
        if ("Laki-Laki".equals(jenisKelamin)) {
            rbLaki.setSelected(true);
            rbPerempuan.setSelected(false);
        } else if ("Perempuan".equals(jenisKelamin)) {
            rbLaki.setSelected(false);
            rbPerempuan.setSelected(true);
        }
        tfalamat.setText(model.getValueAt(selectedRow, 3).toString());
        tfnotelepon.setText(model.getValueAt(selectedRow, 4).toString());
       
        
    }//GEN-LAST:event_tbldatapembeliMouseClicked

    private void btCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCLEARActionPerformed
        tfidpembeli.setText("");
        tfnamalengkap.setText("");
        rbLaki.setSelected(false);
        rbPerempuan.setSelected(false);
        tfalamat.setText("");
        tfnotelepon.setText("");
        tfidpembeli.requestFocus();
    }//GEN-LAST:event_btCLEARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menuutama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCLEAR;
    private javax.swing.JButton btcetak;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tbldatapembeli;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfidpembeli;
    private javax.swing.JTextField tfnamalengkap;
    private javax.swing.JTextField tfnotelepon;
    // End of variables declaration//GEN-END:variables

   
}
